---
Name: customroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'profile//$Action/$ID/$OtherID' : 'ProfileController'
    'passwordadmin//$Action/$ID/$OtherID' : 'PasswordAdminController'